### ISSUE TITLE
...

### ISSUE THREAD

**Issue by MrKpbIcep** [MrKwabs/Airstrikes#1]
https://github.com/MrKwabs/Airstrikes/blob/f44bfa272ab04b2c75bb698c298a0113d11dd7bb/Airstrikes.cs#L138

Instance.Configuration.Instance.StrikeCount + 1 ?

**Comment by DominicTurner02** [comment]
Fixed in newest build; https://harbor.rocketmod.net/plugins/advancedairstrikes/

Thanks for pointing it out.
